name = "peekmd"
main = "src/worker.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "PAGES"
id = "fcaf0070253b484d8b5349957ba5b9cf"
preview_id = "dc1bb955f5e84ddea2925ad197ddab96"

routes = [
  { pattern = "peekmd.dev", custom_domain = true },
]

[vars]
BASE_URL = "https://peekmd.dev"
